export type BookInfo = {
    title: string;
    short_name: string;
    book_number: number;
    chapter_count: number;
    deuterocanonical: boolean;
    deuterocanonical_chapter_count?: number;
};

export const bibleBooks: Array<BookInfo> = [
    {
        title: 'Genesis',
        short_name: 'Gen',
        book_number: 10,
        chapter_count: 50,
        deuterocanonical: false,
    },
    {
        title: 'Exodus',
        short_name: 'Exo',
        book_number: 20,
        chapter_count: 40,
        deuterocanonical: false,
    },
    {
        title: 'Leviticus',
        short_name: 'Lev',
        book_number: 30,
        chapter_count: 27,
        deuterocanonical: false,
    },
    {
        title: 'Numbers',
        short_name: 'Num',
        book_number: 40,
        chapter_count: 36,
        deuterocanonical: false,
    },
    {
        title: 'Deuteronomy',
        short_name: 'Deu',
        book_number: 50,
        chapter_count: 34,
        deuterocanonical: false,
    },
    {
        title: 'Joshua',
        short_name: 'Josh',
        book_number: 60,
        chapter_count: 24,
        deuterocanonical: false,
    },
    {
        title: 'Judges',
        short_name: 'Judg',
        book_number: 70,
        chapter_count: 21,
        deuterocanonical: false,
    },
    {
        title: 'Ruth',
        short_name: 'Ruth',
        book_number: 80,
        chapter_count: 4,
        deuterocanonical: false,
    },
    {
        title: '1 Samuel',
        short_name: '1Sam',
        book_number: 90,
        chapter_count: 31,
        deuterocanonical: false,
    },
    {
        title: '2 Samuel',
        short_name: '2Sam',
        book_number: 100,
        chapter_count: 24,
        deuterocanonical: false,
    },
    {
        title: '1 Kings',
        short_name: '1Kin',
        book_number: 110,
        chapter_count: 22,
        deuterocanonical: false,
    },
    {
        title: '2 Kings',
        short_name: '2Kin',
        book_number: 120,
        chapter_count: 25,
        deuterocanonical: false,
    },
    {
        title: '1 Chronicles',
        short_name: '1Chr',
        book_number: 130,
        chapter_count: 29,
        deuterocanonical: false,
    },
    {
        title: '2 Chronicles',
        short_name: '2Chr',
        book_number: 140,
        chapter_count: 36,
        deuterocanonical: false,
    },
    {
        title: 'Ezra',
        short_name: 'Ezr',
        book_number: 150,
        chapter_count: 10,
        deuterocanonical: false,
    },
    {
        title: 'Nehemiah',
        short_name: 'Neh',
        book_number: 160,
        chapter_count: 13,
        deuterocanonical: false,
    },
    {
        title: 'Tobit',
        short_name: 'Tob',
        book_number: 170,
        chapter_count: 17,
        deuterocanonical: true,
    },
    {
        title: 'Judith',
        short_name: 'Jud',
        book_number: 180,
        chapter_count: 4,
        deuterocanonical: true,
    },
    {
        title: 'Esther',
        short_name: 'Esth',
        book_number: 190,
        chapter_count: 10,
        deuterocanonical: false,
    },
    {
        title: 'Job',
        short_name: 'Job',
        book_number: 220,
        chapter_count: 42,
        deuterocanonical: false,
    },
    {
        title: 'Psalms',
        short_name: 'Ps',
        book_number: 230,
        chapter_count: 150,
        deuterocanonical: false,
    },
    {
        title: 'Proverbs',
        short_name: 'Prov',
        book_number: 240,
        chapter_count: 31,
        deuterocanonical: false,
    },
    {
        title: 'Ecclesiastes',
        short_name: 'Eccl',
        book_number: 250,
        chapter_count: 12,
        deuterocanonical: false,
    },
    {
        title: 'Song of Solomon',
        short_name: 'Song',
        book_number: 260,
        chapter_count: 8,
        deuterocanonical: false,
    },
    {
        title: 'Wisdom',
        short_name: 'Wis',
        book_number: 270,
        chapter_count: 19,
        deuterocanonical: true,
    },
    {
        title: 'Sirach',
        short_name: 'Sir',
        book_number: 280,
        chapter_count: 51,
        deuterocanonical: true,
    },
    {
        title: 'Isaiah',
        short_name: 'Isa',
        book_number: 290,
        chapter_count: 66,
        deuterocanonical: false,
    },
    {
        title: 'Jeremiah',
        short_name: 'Jer',
        book_number: 300,
        chapter_count: 52,
        deuterocanonical: false,
    },
    {
        title: 'Lamentations',
        short_name: 'Lam',
        book_number: 310,
        chapter_count: 5,
        deuterocanonical: false,
    },
    {
        title: 'Baruch',
        short_name: 'Bar',
        book_number: 320,
        chapter_count: 6,
        deuterocanonical: true,
    },
    {
        title: 'Ezekiel',
        short_name: 'Ezek',
        book_number: 330,
        chapter_count: 48,
        deuterocanonical: false,
    },
    {
        title: 'Daniel',
        short_name: 'Dan',
        book_number: 340,
        chapter_count: 12,
        deuterocanonical_chapter_count: 14,
        deuterocanonical: false,
    },
    {
        title: 'Hosea',
        short_name: 'Hos',
        book_number: 350,
        chapter_count: 14,
        deuterocanonical: false,
    },
    {
        title: 'Joel',
        short_name: 'Joel',
        book_number: 360,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: 'Amos',
        short_name: 'Am',
        book_number: 370,
        chapter_count: 9,
        deuterocanonical: false,
    },
    {
        title: 'Obadiah',
        short_name: 'Oba',
        book_number: 380,
        chapter_count: 1,
        deuterocanonical: false,
    },
    {
        title: 'Jonah',
        short_name: 'Jona',
        book_number: 390,
        chapter_count: 4,
        deuterocanonical: false,
    },
    {
        title: 'Micah',
        short_name: 'Mic',
        book_number: 400,
        chapter_count: 7,
        deuterocanonical: false,
    },
    {
        title: 'Nahum',
        short_name: 'Nah',
        book_number: 410,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: 'Habakkuk',
        short_name: 'Hab',
        book_number: 420,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: 'Zephaniah',
        short_name: 'Zeph',
        book_number: 430,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: 'Haggai',
        short_name: 'Hag',
        book_number: 440,
        chapter_count: 2,
        deuterocanonical: false,
    },
    {
        title: 'Zechariah',
        short_name: 'Zech',
        book_number: 450,
        chapter_count: 14,
        deuterocanonical: false,
    },
    {
        title: 'Malachi',
        short_name: 'Mal',
        book_number: 460,
        chapter_count: 4,
        deuterocanonical: false,
    },
    {
        title: '1 Maccabees',
        short_name: '1Ma',
        book_number: 462,
        chapter_count: 16,
        deuterocanonical: true,
    },
    {
        title: '2 Maccabees',
        short_name: '2Ma',
        book_number: 464,
        chapter_count: 16,
        deuterocanonical: true,
    },
    {
        title: 'Matthew',
        short_name: 'Mat',
        book_number: 470,
        chapter_count: 28,
        deuterocanonical: false,
    },
    {
        title: 'Mark',
        short_name: 'Mar',
        book_number: 480,
        chapter_count: 16,
        deuterocanonical: false,
    },
    {
        title: 'Luke',
        short_name: 'Luk',
        book_number: 490,
        chapter_count: 24,
        deuterocanonical: false,
    },
    {
        title: 'John',
        short_name: 'John',
        book_number: 500,
        chapter_count: 21,
        deuterocanonical: false,
    },
    {
        title: 'Acts',
        short_name: 'Acts',
        book_number: 510,
        chapter_count: 28,
        deuterocanonical: false,
    },
    {
        title: 'Romans',
        short_name: 'Rom',
        book_number: 520,
        chapter_count: 16,
        deuterocanonical: false,
    },
    {
        title: '1 Corinthians',
        short_name: '1Cor',
        book_number: 530,
        chapter_count: 16,
        deuterocanonical: false,
    },
    {
        title: '2 Corinthians',
        short_name: '2Cor',
        book_number: 540,
        chapter_count: 13,
        deuterocanonical: false,
    },
    {
        title: 'Galatians',
        short_name: 'Gal',
        book_number: 550,
        chapter_count: 6,
        deuterocanonical: false,
    },
    {
        title: 'Ephesians',
        short_name: 'Eph',
        book_number: 560,
        chapter_count: 6,
        deuterocanonical: false,
    },
    {
        title: 'Philippians',
        short_name: 'Phil',
        book_number: 570,
        chapter_count: 4,
        deuterocanonical: false,
    },
    {
        title: 'Colossians',
        short_name: 'Col',
        book_number: 580,
        chapter_count: 4,
        deuterocanonical: false,
    },
    {
        title: '1 Thessalonians',
        short_name: '1Ths',
        book_number: 590,
        chapter_count: 5,
        deuterocanonical: false,
    },
    {
        title: '2 Thessalonians',
        short_name: '2Ths',
        book_number: 600,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: '1 Timothy',
        short_name: '1Tim',
        book_number: 610,
        chapter_count: 6,
        deuterocanonical: false,
    },
    {
        title: '2 Timothy',
        short_name: '2Tim',
        book_number: 620,
        chapter_count: 4,
        deuterocanonical: false,
    },
    {
        title: 'Titus',
        short_name: 'Tit',
        book_number: 630,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: 'Philemon',
        short_name: 'Phlm',
        book_number: 640,
        chapter_count: 1,
        deuterocanonical: false,
    },
    {
        title: 'Hebrews',
        short_name: 'Heb',
        book_number: 650,
        chapter_count: 13,
        deuterocanonical: false,
    },
    {
        title: 'James',
        short_name: 'Jam',
        book_number: 660,
        chapter_count: 5,
        deuterocanonical: false,
    },
    {
        title: '1 Peter',
        short_name: '1Pet',
        book_number: 670,
        chapter_count: 5,
        deuterocanonical: false,
    },
    {
        title: '2 Peter',
        short_name: '2Pet',
        book_number: 680,
        chapter_count: 3,
        deuterocanonical: false,
    },
    {
        title: '1 John',
        short_name: '1Jn',
        book_number: 690,
        chapter_count: 5,
        deuterocanonical: false,
    },
    {
        title: '2 John',
        short_name: '2Jn',
        book_number: 700,
        chapter_count: 1,
        deuterocanonical: false,
    },
    {
        title: '3 John',
        short_name: '3Jn',
        book_number: 710,
        chapter_count: 1,
        deuterocanonical: false,
    },
    {
        title: 'Jude',
        short_name: 'Jud',
        book_number: 720,
        chapter_count: 1,
        deuterocanonical: false,
    },
    {
        title: 'Revelation',
        short_name: 'Rev',
        book_number: 730,
        chapter_count: 22,
        deuterocanonical: false,
    },
];
