export default {
    file_name: `NASB+.SQLite3`,
    description: `New American Standard Bible`,
    chapter_string: `Chapter`,
    language: `en`,
    russian_numbering: false,
    strong_numbers: true,
    right_to_left: false,
    contains_accents: true,
    detailed_info: `<h2>Holy Bible</h2> <h3>New American Standard Bible</h3> Lockman Foundation, 1995 <p/> with Strong's Numbers, Formatted, Red letter edition`,
    introduction_string: `About edition`,
    chapter_string_ps: `Psalm`,
    history_of_changes: [
        `(2016-09-16) Added Psalm`,
        `(2016-04-05) Code correcion`,
        `(2016-02-18) Code cleaning`,
        `(2015-12-31) corrected Red letters`,
        `(2015-11-27) Correction of Red Color Words of Jesus`,
        `(2015-08-17) Description is renewed`,
        `(2015-08-14) Changed to the requirements of MyBible 4.4`,
        `(2015-03-09) Strong number new code`,
        `(2014-10-06) 2John was actually 3John, fixed, unfortunateely 2John without Strong's numbers`,
        `(2014-09-02) Fixed red letter errors`,
        `(2014-08-31) Fixed red letter errors`,
        `(2014-08-14) Published`,
    ],
};
