// Bump this number whenever you add OR edit any devotional entry
export const DEVOTIONALS_DATA_VERSION = 1;

export const devotionalsData: Array<{
    day_number: number;
    title: string;
    pause: string;
    listen: string;
    think: string;
    pray: string;
    go_action: string;
    verses: string;
}> = [
    // ===== APRIL: Resurrection, New Life, Easter, Victory =====
    {
        day_number: 91,
        title: 'A New Season of Hope',
        pause: '<p>Take a deep breath. Let the worries of yesterday fade. God is doing something new in your life today. Be still and know that He is God.</p>',
        listen: '<p>"See, I am doing a new thing! Now it springs up; do you not perceive it? I am making a way in the wilderness and streams in the wasteland."</p><span class="verse-ref">Isaiah 43:19</span>',
        think: '<p>April marks a season of renewal. Trees bud, flowers bloom, and creation itself declares that God specializes in making all things new. Whatever barren season you have walked through, God is faithful to bring forth life again.</p><p>The same God who commands spring to come after winter is working behind the scenes in your life. Trust His timing. The new thing He promised is already springing up.</p>',
        pray: '<p>Lord, open my eyes to see the new things You are doing in my life. Help me trust Your timing even when the season feels long. I choose to believe that You are making a way where there seems to be none. In Jesus\' name, Amen.</p>',
        go_action: '<p>Write down one area of your life where you need God to do something new. Place it somewhere visible and pray over it this week.</p>',
        verses: '["Isaiah:43:19","Lamentations:3:22-23","Revelation:21:5"]',
    },
    {
        day_number: 92,
        title: 'The Power of the Resurrection',
        pause: '<p>Close your eyes. Picture the empty tomb on that first Easter morning. The stone rolled away. Death defeated. Let that reality sink deep into your heart.</p>',
        listen: '<p>"I want to know Christ — yes, to know the power of his resurrection and participation in his sufferings, becoming like him in his death, and so, somehow, attaining to the resurrection from the dead."</p><span class="verse-ref">Philippians 3:10-11</span>',
        think: '<p>Paul did not merely want to know about the resurrection — he wanted to <em>experience</em> its power in his daily life. The same power that raised Jesus from the dead lives inside every believer. This is not a distant theological concept; it is a present reality.</p><p>When you face impossible situations, remember: you carry resurrection power within you. The God who conquered the grave is more than able to handle whatever you are walking through today.</p>',
        pray: '<p>Father, I want to know the power of Christ\'s resurrection in my everyday life. Strengthen me by Your Spirit. Let the same power that raised Jesus from the dead work mightily in me today. In Jesus\' name, Amen.</p>',
        go_action: '<p>Identify one area where you feel defeated or hopeless. Speak the truth of the resurrection over it: "The same power that raised Christ from the dead is alive in me."</p>',
        verses: '["Philippians:3:10","Ephesians:1:19-20","Romans:8:11"]',
    },
    {
        day_number: 93,
        title: 'Walking in Newness of Life',
        pause: '<p>Be still for a moment. You are not who you used to be. In Christ, you are a new creation. Let that truth settle in your spirit.</p>',
        listen: '<p>"Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!"</p><span class="verse-ref">2 Corinthians 5:17</span>',
        think: '<p>When you gave your life to Christ, something radical happened — your old identity died, and a brand-new you was born. You are not a cleaned-up version of your former self. You are an entirely new creation with a new nature, a new purpose, and a new destiny.</p><p>Stop looking in the rearview mirror at who you were. God is not holding your past against you. Walk boldly into the newness of life He has prepared for you.</p>',
        pray: '<p>Jesus, thank You for making me new. Help me to stop living as though my old identity still defines me. I receive my new identity in You. Teach me to walk in the fullness of the new creation I have become. Amen.</p>',
        go_action: '<p>Write down three things that are true about your new identity in Christ. Speak them aloud over yourself today.</p>',
        verses: '["2 Corinthians:5:17","Romans:6:4","Galatians:2:20"]',
    },
    {
        day_number: 94,
        title: 'He Carried Our Sorrows',
        pause: '<p>Sit quietly with God. If there is pain or grief in your heart, you do not need to hide it. He already knows, and He cares deeply.</p>',
        listen: '<p>"Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted. But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed."</p><span class="verse-ref">Isaiah 53:4-5</span>',
        think: '<p>Jesus did not merely observe our suffering from a distance. He entered into it fully. On the cross, He took upon Himself every sorrow, every sickness, every sin that weighs us down. He was crushed so that we could be made whole.</p><p>If you are carrying grief or pain today, know that Jesus has already carried it for you. You do not have to bear it alone. Lay your burdens at the foot of the cross and receive the peace that His sacrifice purchased for you.</p>',
        pray: '<p>Lord Jesus, thank You for carrying my pain and sorrows on the cross. I lay every burden at Your feet right now. I receive the healing and peace that Your wounds have purchased for me. Amen.</p>',
        go_action: '<p>Is there a sorrow you have been carrying alone? Tell God about it honestly in prayer, and then write down: "Jesus has carried this for me."</p>',
        verses: '["Isaiah:53:4-5","1 Peter:2:24","Matthew:11:28"]',
    },
    {
        day_number: 95,
        title: 'The Lamb Who Was Slain',
        pause: '<p>Take a moment to reflect on the magnitude of God\'s love. Before the foundation of the world, He already had a plan to rescue you.</p>',
        listen: '<p>"For you know that it was not with perishable things such as silver or gold that you were redeemed from the empty way of life handed down to you from your ancestors, but with the precious blood of Christ, a lamb without blemish or defect."</p><span class="verse-ref">1 Peter 1:18-19</span>',
        think: '<p>Your redemption was not cheap. It cost the precious blood of the spotless Lamb of God. No amount of silver or gold could buy your freedom — only the sinless life of Jesus was sufficient to pay the price for your salvation.</p><p>When you begin to doubt your worth, remember the price that was paid for you. God did not spare His own Son because He considered you worth the sacrifice. You are that valuable to Him.</p>',
        pray: '<p>Father, I stand in awe of the price You paid for my redemption. Thank You for not sparing Your own Son but giving Him freely for me. Help me to live in a way that honors the precious blood of Jesus. Amen.</p>',
        go_action: '<p>Spend five minutes meditating on the cost of your salvation. Let gratitude fill your heart and shape how you treat others today.</p>',
        verses: '["1 Peter:1:18-19","Revelation:5:12","John:1:29"]',
    },
    {
        day_number: 96,
        title: 'From Darkness to Marvelous Light',
        pause: '<p>Close your eyes. Remember where you were before Christ found you. Now open them. Thank God for the light He has brought into your life.</p>',
        listen: '<p>"But you are a chosen people, a royal priesthood, a holy nation, God\'s special possession, that you may declare the praises of him who called you out of darkness into his wonderful light."</p><span class="verse-ref">1 Peter 2:9</span>',
        think: '<p>You were not pulled from darkness by accident. God <em>chose</em> you. He called you by name and brought you out of the shadows into His marvelous light. You are not a bystander in God\'s story — you are His special possession, set apart for a holy purpose.</p><p>Your identity is not based on your performance. You are chosen, royal, holy, and treasured. Let that truth define how you see yourself and how you walk through this day.</p>',
        pray: '<p>God, thank You for choosing me and calling me out of darkness. I receive my identity as Your special possession. Help me to walk as a child of light today and declare Your praises in everything I do. In Jesus\' name, Amen.</p>',
        go_action: '<p>Share your testimony with someone today — even a brief word about how God brought light into your darkness.</p>',
        verses: '["1 Peter:2:9","Ephesians:5:8","Colossians:1:13"]',
    },
    {
        day_number: 97,
        title: 'The Stone That Was Rolled Away',
        pause: '<p>Breathe deeply. Think of a situation in your life that feels sealed shut, like a stone blocking the way. Invite God into that space.</p>',
        listen: '<p>"When they looked up, they saw that the stone, which was very large, had been rolled away."</p><span class="verse-ref">Mark 16:4</span>',
        think: '<p>The women who went to the tomb that Sunday morning were worried about who would roll away the stone. It was massive, immovable by human strength. But when they arrived, the work was already done. God had moved the stone before they even got there.</p><p>Are you worried about obstacles that seem too big to move? God is already working ahead of you. The stone you are stressing about may already be rolled away by the time you arrive. Trust Him.</p>',
        pray: '<p>Lord, I bring You the stones in my life — the obstacles that feel immovable. I trust that You are already working ahead of me. Give me faith to keep walking forward, knowing that You will make a way. Amen.</p>',
        go_action: '<p>Name your "stone" — the biggest obstacle you face right now. Release it to God and take one step of faith toward it today.</p>',
        verses: '["Mark:16:4","Matthew:28:2","Luke:1:37"]',
    },
    {
        day_number: 98,
        title: 'Do Not Be Afraid',
        pause: '<p>Let your shoulders relax. Release the tension in your body. Hear the angel\'s words echo across the centuries: "Do not be afraid."</p>',
        listen: '<p>"The angel said to the women, \'Do not be afraid, for I know that you are looking for Jesus, who was crucified. He is not here; he has risen, just as he said.\'"</p><span class="verse-ref">Matthew 28:5-6</span>',
        think: '<p>Fear is a natural human response to uncertainty. The women at the tomb were terrified. But the angel\'s first words were not a rebuke — they were comfort. God meets us in our fear with reassurance, not condemnation.</p><p>Whatever makes you afraid today — an uncertain future, a health concern, a broken relationship — hear God say to you: "Do not be afraid." The One who conquered death is with you. There is nothing you will face that He has not already overcome.</p>',
        pray: '<p>Father, I confess my fears to You. I choose to trust the risen Christ rather than my circumstances. Replace my fear with faith, my anxiety with peace, and my doubt with confidence in Your promises. In Jesus\' name, Amen.</p>',
        go_action: '<p>Every time fear rises today, pause and whisper: "He is risen. I do not need to be afraid."</p>',
        verses: '["Matthew:28:5-6","Isaiah:41:10","2 Timothy:1:7"]',
    },
    {
        day_number: 99,
        title: 'The Garden and the Tomb',
        pause: '<p>Imagine yourself in a quiet garden at dawn. The air is cool, the birds are beginning to sing. Jesus is near. Rest in His presence.</p>',
        listen: '<p>"Now Mary stood outside the tomb crying... She turned around and saw Jesus standing there, but she did not realize that it was Jesus. He asked her, \'Woman, why are you crying? Who is it you are looking for?\'"</p><span class="verse-ref">John 20:11,14-15</span>',
        think: '<p>Mary Magdalene came to the tomb weeping, certain that all hope was lost. She was so consumed by grief that she did not recognize Jesus standing right in front of her. It was only when He spoke her name that her eyes were opened.</p><p>Sometimes our pain can blind us to God\'s presence. He is closer than you think — often standing right beside you in your darkest moment. Listen for His voice. He knows your name, and He is calling you out of sorrow into joy.</p>',
        pray: '<p>Jesus, open my eyes to see You even in the midst of my tears. Speak my name and remind me that You are near. Turn my mourning into dancing and my sorrow into joy. Amen.</p>',
        go_action: '<p>Find a quiet place today — even five minutes — and simply listen for God\'s voice. He may speak through Scripture, a thought, or a deep sense of peace.</p>',
        verses: '["John:20:11-16","Psalm:30:5","Isaiah:61:3"]',
    },
    {
        day_number: 100,
        title: 'Alive Forevermore',
        pause: '<p>This is day 100. A milestone in this year\'s journey with God. Pause and thank Him for every step that has brought you here.</p>',
        listen: '<p>"I am the Living One; I was dead, and now look, I am alive for ever and ever! And I hold the keys of death and Hades."</p><span class="verse-ref">Revelation 1:18</span>',
        think: '<p>Jesus is not a historical figure who lived and died two thousand years ago. He is the Living One — alive right now, reigning in glory, holding the keys of death and the grave. No other religious leader can make this claim. The tomb is empty, and our Savior lives.</p><p>Because He lives, we can face tomorrow. Because He holds the keys, death has no power over us. Every fear, every enemy, every obstacle is subject to the One who is alive forevermore.</p>',
        pray: '<p>Jesus, You are alive! I worship You as the Living One who holds all authority. Because You live, I have hope. Because You reign, I have peace. Thank You for the assurance of eternal life. Amen.</p>',
        go_action: '<p>Celebrate this milestone. Tell someone today: "Jesus is alive, and that changes everything."</p>',
        verses: '["Revelation:1:18","John:11:25","Romans:6:9"]',
    },
    {
        day_number: 101,
        title: 'Doubts Do Not Disqualify You',
        pause: '<p>If you have ever wrestled with doubt, you are in good company. Even the disciples doubted. Come as you are — God welcomes honest questions.</p>',
        listen: '<p>"Then he said to Thomas, \'Put your finger here; see my hands. Reach out your hand and put it into my side. Stop doubting and believe.\' Thomas said to him, \'My Lord and my God!\'"</p><span class="verse-ref">John 20:27-28</span>',
        think: '<p>Jesus did not reject Thomas for doubting. Instead, He met Thomas exactly where he was and offered the evidence he needed. God is not threatened by your questions. He is big enough to handle your doubts and patient enough to walk you through them.</p><p>Notice that Thomas\'s doubt, once met by the risen Christ, produced one of the most powerful confessions of faith in all of Scripture: "My Lord and my God!" Your wrestle with doubt may be the very thing that leads you to a deeper faith.</p>',
        pray: '<p>Lord, I bring my doubts and questions to You honestly. Meet me where I am. Strengthen my faith and help me to see You clearly. Like Thomas, I want to say with my whole heart: "My Lord and my God!" Amen.</p>',
        go_action: '<p>Write down one doubt or question you have been afraid to bring to God. Bring it to Him in prayer today — He is not offended by your honesty.</p>',
        verses: '["John:20:27-28","Mark:9:24","Jude:1:22"]',
    },
    {
        day_number: 102,
        title: 'The Road to Emmaus',
        pause: '<p>Think about a time when you were discouraged and confused about God\'s plan. Even in those moments, Jesus was walking beside you.</p>',
        listen: '<p>"As they talked and discussed these things with each other, Jesus himself came up and walked along with them; but they were kept from recognizing him."</p><span class="verse-ref">Luke 24:15-16</span>',
        think: '<p>Two disciples walked the road to Emmaus, heartbroken and confused after the crucifixion. They had hoped Jesus was the Messiah, but now He was dead. What they did not realize was that the risen Jesus was walking right beside them, patiently listening and teaching.</p><p>In your seasons of confusion, Jesus is not absent — He is present, walking alongside you. He may reveal Himself in unexpected ways: through Scripture, through a friend, or through a sudden moment of clarity. Keep walking and keep your heart open.</p>',
        pray: '<p>Jesus, even when I cannot see You or feel You, I choose to believe You are walking with me. Open my eyes to recognize Your presence on the road. Set my heart on fire with Your Word. Amen.</p>',
        go_action: '<p>Go for a walk today — even a short one — and talk to Jesus as if He were walking right beside you. He is.</p>',
        verses: '["Luke:24:15-16","Luke:24:32","Matthew:28:20"]',
    },
    {
        day_number: 103,
        title: 'Peace Be With You',
        pause: '<p>Inhale slowly. Exhale. Receive the peace of Christ. It is not the absence of trouble — it is the presence of God in the midst of trouble.</p>',
        listen: '<p>"On the evening of that first day of the week, when the disciples were together, with the doors locked for fear of the Jewish leaders, Jesus came and stood among them and said, \'Peace be with you!\'"</p><span class="verse-ref">John 20:19</span>',
        think: '<p>The disciples were hiding behind locked doors, paralyzed by fear. But locked doors are no obstacle for the risen Christ. He walked right through them and spoke peace into their terror. His first word to frightened people was not a command — it was a gift: <em>peace</em>.</p><p>No matter how tightly you have locked the doors of your heart out of fear, Jesus can reach you. He comes not to judge you for being afraid, but to fill you with a peace that the world cannot give and cannot take away.</p>',
        pray: '<p>Prince of Peace, I open the locked doors of my heart to You. Come in and fill every fearful corner with Your presence. I receive Your peace — not as the world gives, but as only You can give. Amen.</p>',
        go_action: '<p>Is there someone in your life who needs to hear "peace be with you" today? Send them an encouraging message or call them.</p>',
        verses: '["John:20:19","John:14:27","Philippians:4:7"]',
    },
    {
        day_number: 104,
        title: 'Scars That Tell a Story',
        pause: '<p>Look at your hands. Every line, every mark tells a story. Jesus chose to keep His scars. They are proof of a love that conquered death.</p>',
        listen: '<p>"Then he said to Thomas, \'Put your finger here; see my hands. Reach out your hand and put it into my side.\'"</p><span class="verse-ref">John 20:27</span>',
        think: '<p>When Jesus rose from the dead, He could have had a completely new, unmarked body. Instead, He kept His scars. He showed them to His disciples as proof — not of defeat, but of victory. His wounds are evidence that love went all the way and won.</p><p>Your scars — the wounds from past pain, failures, and heartbreaks — are not signs of weakness. In God\'s hands, they become a testimony. They tell the story of what you survived by His grace. Do not be ashamed of them; they are part of your resurrection story.</p>',
        pray: '<p>Jesus, thank You for Your scars that purchased my healing. Help me see my own wounds not as reasons for shame, but as testimonies of Your faithfulness. Use my story to encourage others. Amen.</p>',
        go_action: '<p>Think of a scar — physical or emotional — that God has redeemed. Thank Him for turning your pain into a testimony.</p>',
        verses: '["John:20:27","2 Corinthians:12:9","Psalm:147:3"]',
    },
    {
        day_number: 105,
        title: 'Breakfast by the Shore',
        pause: '<p>Picture the Sea of Galilee at dawn. A charcoal fire on the beach. The smell of fresh bread and fish. Jesus is cooking breakfast for His friends.</p>',
        listen: '<p>"Jesus said to them, \'Come and have breakfast.\' None of the disciples dared ask him, \'Who are you?\' They knew it was the Lord."</p><span class="verse-ref">John 21:12</span>',
        think: '<p>After His resurrection, Jesus did not summon His disciples to a palace or a throne room. He met them on a beach and made them breakfast. The King of Kings served fish and bread to tired, confused fishermen. This is the heart of our God — present in the ordinary, meeting us in our everyday needs.</p><p>God cares about the mundane details of your life. He is not only the God of miracles and grand moments. He is the God of breakfast, of daily provision, of quiet companionship by the shore.</p>',
        pray: '<p>Lord, thank You for meeting me in the ordinary moments. Help me to recognize Your presence in the daily routines of life — in meals, in conversations, in quiet mornings. You are the God of the everyday. Amen.</p>',
        go_action: '<p>Prepare a meal for someone today — a friend, a family member, a neighbor. Let it be an act of love that mirrors the heart of Jesus.</p>',
        verses: '["John:21:12","John:21:15-17","Psalm:23:5"]',
    },
    {
        day_number: 106,
        title: 'Do You Love Me?',
        pause: '<p>Let God ask you the same question He asked Peter: "Do you love Me?" Do not rush to answer. Sit with it. Let it search your heart.</p>',
        listen: '<p>"When they had finished eating, Jesus said to Simon Peter, \'Simon son of John, do you love me more than these?\' \'Yes, Lord,\' he said, \'you know that I love you.\' Jesus said, \'Feed my lambs.\'"</p><span class="verse-ref">John 21:15</span>',
        think: '<p>Peter had denied Jesus three times. Now, the risen Jesus gave him three opportunities to reaffirm his love. This was not an interrogation — it was restoration. Every "Do you love Me?" was an invitation to replace a denial with a declaration of love.</p><p>If you have failed God, He is not keeping score. He is offering you a fresh start. He does not ask for perfection — He asks for love. And each time you say "yes" to Him, He entrusts you with greater purpose: "Feed my sheep."</p>',
        pray: '<p>Jesus, You know all things — You know that I love You, even imperfectly. Thank You for restoring me after my failures. I say yes to You again today. Show me how to serve others from the overflow of that love. Amen.</p>',
        go_action: '<p>Has failure made you feel disqualified? Write "He restores me" somewhere you will see it today. Then do something kind for someone as an act of renewed purpose.</p>',
        verses: '["John:21:15-17","Psalm:51:12","Lamentations:3:22-23"]',
    },
    {
        day_number: 107,
        title: 'The Promise of the Spirit',
        pause: '<p>Be still. The same Holy Spirit who empowered the early church lives within you right now. Acknowledge His presence.</p>',
        listen: '<p>"But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth."</p><span class="verse-ref">Acts 1:8</span>',
        think: '<p>Before ascending to heaven, Jesus promised His followers something extraordinary: the Holy Spirit. Not a distant force, but a personal Presence who would empower them to do things beyond their natural ability. This promise was for them — and it is for you.</p><p>You are not meant to live the Christian life in your own strength. The Holy Spirit is your helper, your comforter, your guide, and your source of supernatural power. Lean into Him today.</p>',
        pray: '<p>Holy Spirit, fill me afresh today. I cannot live this life in my own strength. I need Your power, Your guidance, and Your comfort. Empower me to be a faithful witness wherever I go. In Jesus\' name, Amen.</p>',
        go_action: '<p>Before making any decision today, pause and ask the Holy Spirit: "What would You have me do?" Then listen.</p>',
        verses: '["Acts:1:8","John:14:26","Romans:8:26"]',
    },
    {
        day_number: 108,
        title: 'Seeds Must Fall and Die',
        pause: '<p>Hold a seed in your mind\'s eye — small, unremarkable, lifeless in appearance. Yet within it lies an entire harvest. Be patient with what God is growing in you.</p>',
        listen: '<p>"Very truly I tell you, unless a kernel of wheat falls to the ground and dies, it remains only a single seed. But if it dies, it produces many seeds."</p><span class="verse-ref">John 12:24</span>',
        think: '<p>Jesus spoke these words about His own death and resurrection, but the principle extends to our lives. Growth requires letting go. Fruitfulness requires dying to self — to our pride, our plans, our desire for control. It is in the surrendered places that God produces the greatest harvest.</p><p>The things you are releasing right now — comfort, certainty, old habits — are seeds being planted. Trust the process. What looks like death is actually the beginning of abundant new life.</p>',
        pray: '<p>Lord, give me the courage to let go of what You are asking me to release. I trust that what dies in Your hands does not stay dead — it becomes a harvest. Help me surrender fully. Amen.</p>',
        go_action: '<p>Identify one thing God is asking you to let go of. Write it on a piece of paper, pray over it, and symbolically release it to God.</p>',
        verses: '["John:12:24","Galatians:2:20","Mark:8:35"]',
    },
    {
        day_number: 109,
        title: 'He Prepares a Table for You',
        pause: '<p>Rest. Even in the middle of your battles, God has set a table for you. You are invited to sit down and feast in His presence.</p>',
        listen: '<p>"You prepare a table before me in the presence of my enemies. You anoint my head with oil; my cup overflows."</p><span class="verse-ref">Psalm 23:5</span>',
        think: '<p>Notice where the table is set — not after the battle, but <em>in the presence of your enemies</em>. God does not wait until your problems are solved to bless you. He blesses you right in the middle of the struggle. His provision, peace, and abundance are available even in the fight.</p><p>The enemy wants you to believe you are starving and abandoned. But God has set a feast before you. Sit down. Eat. Let your cup overflow. The battle belongs to the Lord.</p>',
        pray: '<p>Good Shepherd, thank You for preparing a table for me even when enemies surround me. I choose to feast on Your goodness rather than focus on my problems. My cup overflows with Your blessings. Amen.</p>',
        go_action: '<p>Instead of worrying about a current problem, intentionally thank God for three specific blessings in your life right now.</p>',
        verses: '["Psalm:23:5","Psalm:23:1-6","Romans:8:37"]',
    },
    {
        day_number: 110,
        title: 'From Mourning to Dancing',
        pause: '<p>Think about a time when your heart was heavy. Now think about a time when joy returned. God is the One who turns our mourning into dancing.</p>',
        listen: '<p>"You turned my wailing into dancing; you removed my sackcloth and clothed me with joy, that my heart may sing your praises and not be silent. Lord my God, I will praise you forever."</p><span class="verse-ref">Psalm 30:11-12</span>',
        think: '<p>The resurrection is the ultimate picture of mourning turned to dancing. The disciples went from devastating grief on Friday to uncontainable joy on Sunday. God did not remove the pain — He transformed it. He walked them through it and brought them out the other side with something greater.</p><p>If you are in a season of weeping, hold on. Joy is coming. It may not come on your timeline, but it will come. God is faithful to complete the work He has started in you.</p>',
        pray: '<p>Father, I trust that You are turning my mourning into dancing. Even if I cannot see it yet, I believe that joy is on the way. Clothe me with gladness and let my heart sing Your praises. Amen.</p>',
        go_action: '<p>Put on a worship song and let yourself be moved. Sing, clap, or dance — even if it feels small. Choose joy today as an act of faith.</p>',
        verses: '["Psalm:30:11-12","Jeremiah:31:13","John:16:20"]',
    },
    {
        day_number: 111,
        title: 'The Cross Before the Crown',
        pause: '<p>Reflect on this: there is no crown without a cross, no victory without a battle, no resurrection without a crucifixion. God uses the hard places.</p>',
        listen: '<p>"For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God."</p><span class="verse-ref">Hebrews 12:2</span>',
        think: '<p>Jesus endured the worst the world could throw at Him — betrayal, mockery, torture, death — because He could see beyond the cross to the joy that awaited. He kept His eyes on the eternal reward and endured the temporary suffering.</p><p>Your present difficulties are not the end of the story. Like Jesus, you can endure the hard season because there is joy set before you. Keep your eyes on what God has promised, not on what you are currently walking through.</p>',
        pray: '<p>Jesus, when the road is painful, help me to fix my eyes on You. Give me the strength to endure with grace, knowing that joy awaits on the other side. I trust Your process. Amen.</p>',
        go_action: '<p>Write Hebrews 12:2 on a card and place it where you will see it. Let it remind you that endurance leads to joy.</p>',
        verses: '["Hebrews:12:2","James:1:2-4","Romans:8:18"]',
    },
    {
        day_number: 112,
        title: 'Grafted Into the Vine',
        pause: '<p>Picture a vine with many branches, each one connected, each one alive because of the sap flowing from the root. You are one of those branches.</p>',
        listen: '<p>"I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing."</p><span class="verse-ref">John 15:5</span>',
        think: '<p>A branch does not produce fruit by straining or trying harder. It produces fruit by staying connected to the vine. The life, the nutrients, the growth — all of it comes from the vine. The branch\'s only job is to remain attached.</p><p>In a world that prizes hustle and self-sufficiency, Jesus invites us to a different way: abide. Stay connected. Rest in Him. The fruit will come naturally as you remain in His love, His Word, and His presence.</p>',
        pray: '<p>Jesus, I want to remain in You. Forgive me for the times I have tried to produce fruit in my own strength. Teach me to abide in Your presence and trust You with the outcome. Amen.</p>',
        go_action: '<p>Choose one way to abide in Christ today: read a passage of Scripture slowly, spend time in prayer, or sit in silence with Him for ten minutes.</p>',
        verses: '["John:15:5","John:15:4","Galatians:5:22-23"]',
    },
    {
        day_number: 113,
        title: 'The Victory Is Already Won',
        pause: '<p>Take a breath. Whatever battle you are facing, the outcome has already been decided. In Christ, you are on the winning side.</p>',
        listen: '<p>"But thanks be to God! He gives us the victory through our Lord Jesus Christ."</p><span class="verse-ref">1 Corinthians 15:57</span>',
        think: '<p>The resurrection was God\'s ultimate declaration of victory. Death, sin, and the grave — humanity\'s greatest enemies — were defeated once and for all. This victory was not earned by our effort but given to us as a gift through Jesus Christ.</p><p>You do not fight <em>for</em> victory; you fight <em>from</em> victory. The battle has already been won on the cross. When you face temptation, discouragement, or spiritual attack, stand firm in the finished work of Christ. The enemy is already defeated.</p>',
        pray: '<p>Father, thank You for the victory You have already won. I do not fight from a place of fear but from a place of triumph. Help me stand firm in the truth that the battle is already Yours. In Jesus\' name, Amen.</p>',
        go_action: '<p>Replace one negative, fearful thought today with this declaration: "Thanks be to God, who gives me the victory through Jesus Christ."</p>',
        verses: '["1 Corinthians:15:57","Romans:8:37","1 John:5:4"]',
    },
    {
        day_number: 114,
        title: 'Springs of Living Water',
        pause: '<p>Think of a cool, flowing spring of water on a hot day. Let your soul be refreshed. Jesus offers water that never runs dry.</p>',
        listen: '<p>"Whoever believes in me, as Scripture has said, rivers of living water will flow from within them."</p><span class="verse-ref">John 7:38</span>',
        think: '<p>Jesus does not just quench your thirst — He turns you into a source of refreshment for others. The living water He gives is the Holy Spirit, flowing from within you like a river. It is not a trickle; it is an overflowing, life-giving stream.</p><p>When you abide in Christ, you naturally become a blessing to those around you. Your words bring encouragement. Your presence brings peace. Your life points others to the Source. You do not have to force it — just stay connected to the Spring.</p>',
        pray: '<p>Lord Jesus, let rivers of living water flow from within me. Fill me so full of Your Spirit that it overflows to everyone I encounter. Let my life be refreshing to others. Amen.</p>',
        go_action: '<p>Be a "spring of living water" today — offer a cold drink, a kind word, or practical help to someone who looks weary.</p>',
        verses: '["John:7:38","John:4:14","Isaiah:58:11"]',
    },
    {
        day_number: 115,
        title: 'He Makes All Things New',
        pause: '<p>Close your eyes. Think of something in your life that feels old, worn out, or broken. Now hear God whisper: "I am making all things new."</p>',
        listen: '<p>"He who was seated on the throne said, \'I am making everything new!\' Then he said, \'Write this down, for these words are trustworthy and true.\'"</p><span class="verse-ref">Revelation 21:5</span>',
        think: '<p>God does not just patch things up — He makes them <em>new</em>. Not repaired. Not refurbished. Brand new. This is the promise of the One who sits on the throne: total restoration, complete renewal, a future so beautiful that He told John to write it down because it is absolutely trustworthy.</p><p>That broken relationship, that shattered dream, that part of your life that feels beyond repair — God has not given up on it. He is the master Restorer, and He is working even now to bring beauty from ashes.</p>',
        pray: '<p>God, I believe Your promise to make all things new. I bring the broken areas of my life to You. Restore, renew, and rebuild what the enemy has tried to destroy. I trust Your faithful words. Amen.</p>',
        go_action: '<p>Take something broken — a strained friendship, a neglected goal, a forgotten dream — and take one small step toward renewal today.</p>',
        verses: '["Revelation:21:5","Isaiah:61:3","Joel:2:25"]',
    },
    {
        day_number: 116,
        title: 'Forgiven and Set Free',
        pause: '<p>Let go of the guilt. Let go of the shame. Christ has already paid the price. You are forgiven. Receive it.</p>',
        listen: '<p>"Therefore, there is now no condemnation for those who are in Christ Jesus, because through Christ Jesus the law of the Spirit who gives life has set you free from the law of sin and death."</p><span class="verse-ref">Romans 8:1-2</span>',
        think: '<p>No condemnation. Not "less condemnation" or "condemnation on good days." <em>No</em> condemnation — none at all — for those who are in Christ. The gavel has come down, and the verdict is: free. The law of the Spirit of life has broken the chains of sin and death.</p><p>If the enemy whispers that you are still guilty, remind him of the cross. If your own heart condemns you, remember that God is greater than your heart. You are not defined by your worst moment. You are defined by Christ\'s best moment — His sacrifice for you.</p>',
        pray: '<p>Father, I receive Your forgiveness today. I refuse to live under condemnation when Christ has set me free. Help me to walk in the freedom You purchased for me and to extend that same grace to others. Amen.</p>',
        go_action: '<p>If you have been carrying guilt over a confessed sin, write it down and then cross it out. Write over it: "No condemnation — Romans 8:1." Let it go.</p>',
        verses: '["Romans:8:1-2","1 John:1:9","Psalm:103:12"]',
    },
    {
        day_number: 117,
        title: 'The Good Shepherd Leads',
        pause: '<p>Sheep do not need to know the entire path. They only need to know the Shepherd\'s voice. Listen for His voice today.</p>',
        listen: '<p>"My sheep listen to my voice; I know them, and they follow me. I give them eternal life, and they shall never perish; no one will snatch them out of my hand."</p><span class="verse-ref">John 10:27-28</span>',
        think: '<p>Jesus describes a beautiful, intimate relationship between a shepherd and his sheep. He knows you — not just your name, but your heart, your struggles, your dreams. And you can know His voice — distinct, trustworthy, leading you to green pastures and still waters.</p><p>In a world full of competing voices, learn to distinguish the Shepherd\'s voice. He will never lead you into danger. He will never abandon you. And nothing — absolutely nothing — can snatch you from His hand.</p>',
        pray: '<p>Good Shepherd, tune my ears to Your voice above all the noise. I trust You to lead me on the right path. Thank You that I am secure in Your hand and that nothing can take me from You. Amen.</p>',
        go_action: '<p>Practice listening to God today. Before each major moment — a meeting, a conversation, a decision — ask: "Shepherd, what do You want me to know?"</p>',
        verses: '["John:10:27-28","Psalm:23:1-3","Isaiah:30:21"]',
    },
    {
        day_number: 118,
        title: 'Clothed in Righteousness',
        pause: '<p>Imagine removing heavy, dirty garments and being clothed in pure, white robes. This is what Christ has done for you. Receive it.</p>',
        listen: '<p>"I delight greatly in the Lord; my soul rejoices in my God. For he has clothed me with garments of salvation and arrayed me in a robe of his righteousness."</p><span class="verse-ref">Isaiah 61:10</span>',
        think: '<p>You cannot earn righteousness by your own efforts. It is a gift — a robe that God Himself wraps around you. When He looks at you, He does not see your failures and stains. He sees you clothed in the righteousness of Christ, beautiful and blameless.</p><p>Stop trying to clean yourself up before coming to God. He is the one who clothes you. Come as you are, and let Him dress you in salvation and righteousness. Then walk in the confidence that you are already accepted and loved.</p>',
        pray: '<p>Lord, I am grateful that my righteousness comes from You and not from my own works. Thank You for clothing me in salvation. Help me walk today in the confidence of who I am in Christ. Amen.</p>',
        go_action: '<p>The next time you feel "not good enough," remember: you are clothed in His righteousness. Speak it: "I am righteous in Christ — not by my works, but by His grace."</p>',
        verses: '["Isaiah:61:10","2 Corinthians:5:21","Philippians:3:9"]',
    },
    {
        day_number: 119,
        title: 'Hope That Does Not Disappoint',
        pause: '<p>Whatever has disappointed you — a broken promise, an unmet expectation, a delayed dream — know this: the hope God gives will never put you to shame.</p>',
        listen: '<p>"And hope does not put us to shame, because God\'s love has been poured out into our hearts through the Holy Spirit, who has been given to us."</p><span class="verse-ref">Romans 5:5</span>',
        think: '<p>Worldly hope is uncertain — it depends on circumstances, people, and timing. But the hope we have in Christ is anchored in something unshakeable: God\'s love, poured into our hearts by the Holy Spirit. This hope is not wishful thinking; it is confident expectation based on God\'s character.</p><p>Even when life disappoints, God never does. His promises are yes and amen in Christ. The hope He gives is not fragile — it is an anchor for the soul, firm and secure. Hold fast to it.</p>',
        pray: '<p>Father, pour out Your love afresh in my heart today. Anchor my hope in Your promises, not in my circumstances. Thank You that the hope You give will never disappoint. I trust You. Amen.</p>',
        go_action: '<p>Encourage someone who is losing hope today. Share a Bible verse or a word of encouragement. Be a carrier of the hope that does not disappoint.</p>',
        verses: '["Romans:5:5","Hebrews:6:19","Jeremiah:29:11"]',
    },
    {
        day_number: 120,
        title: 'Living as Resurrection People',
        pause: '<p>As this month draws to a close, sit with this truth: you serve a risen Savior. Because of the resurrection, everything has changed. You are alive in Christ.</p>',
        listen: '<p>"Since, then, you have been raised with Christ, set your hearts on things above, where Christ is, seated at the right hand of God. Set your minds on things above, not on earthly things."</p><span class="verse-ref">Colossians 3:1-2</span>',
        think: '<p>The resurrection is not just an event we celebrate once a year — it is a reality we live in every single day. Because Christ was raised, we too have been raised to new life. Our perspective should be shaped by eternity, not just by the temporary circumstances we see around us.</p><p>As resurrection people, we live with hope in despair, peace in chaos, joy in suffering, and love in hatred. We are citizens of heaven, living with purpose on earth. Let this truth shape every decision, every relationship, and every moment of this day.</p>',
        pray: '<p>Risen Lord, help me to live each day as a resurrection person. Set my heart and mind on things above. Let the reality of Your resurrection transform how I see the world and how I walk through it. In Your powerful name, Amen.</p>',
        go_action: '<p>Reflect on this month\'s journey through the resurrection theme. Write down the one truth that impacted you the most. Carry it into the months ahead.</p>',
        verses: '["Colossians:3:1-2","Ephesians:2:6","Romans:6:4"]',
    },
];
