class Book {
  final String title;
  final String shortName;
  final int bookNumber;
  final int chapterCount;
  final bool deuterocanonical;

  const Book({
    required this.title,
    required this.shortName,
    required this.bookNumber,
    required this.chapterCount,
    this.deuterocanonical = false,
  });
}

const List<Book> bibleBooks = [
  Book(title: 'Genesis', shortName: 'Gen', bookNumber: 10, chapterCount: 50),
  Book(title: 'Exodus', shortName: 'Exo', bookNumber: 20, chapterCount: 40),
  Book(title: 'Leviticus', shortName: 'Lev', bookNumber: 30, chapterCount: 27),
  Book(title: 'Numbers', shortName: 'Num', bookNumber: 40, chapterCount: 36),
  Book(title: 'Deuteronomy', shortName: 'Deu', bookNumber: 50, chapterCount: 34),
  Book(title: 'Joshua', shortName: 'Josh', bookNumber: 60, chapterCount: 24),
  Book(title: 'Judges', shortName: 'Judg', bookNumber: 70, chapterCount: 21),
  Book(title: 'Ruth', shortName: 'Ruth', bookNumber: 80, chapterCount: 4),
  Book(title: '1 Samuel', shortName: '1Sam', bookNumber: 90, chapterCount: 31),
  Book(title: '2 Samuel', shortName: '2Sam', bookNumber: 100, chapterCount: 24),
  Book(title: '1 Kings', shortName: '1Kin', bookNumber: 110, chapterCount: 22),
  Book(title: '2 Kings', shortName: '2Kin', bookNumber: 120, chapterCount: 25),
  Book(title: '1 Chronicles', shortName: '1Chr', bookNumber: 130, chapterCount: 29),
  Book(title: '2 Chronicles', shortName: '2Chr', bookNumber: 140, chapterCount: 36),
  Book(title: 'Ezra', shortName: 'Ezr', bookNumber: 150, chapterCount: 10),
  Book(title: 'Nehemiah', shortName: 'Neh', bookNumber: 160, chapterCount: 13),
  Book(title: 'Esther', shortName: 'Esth', bookNumber: 190, chapterCount: 10),
  Book(title: 'Job', shortName: 'Job', bookNumber: 220, chapterCount: 42),
  Book(title: 'Psalms', shortName: 'Ps', bookNumber: 230, chapterCount: 150),
  Book(title: 'Proverbs', shortName: 'Prov', bookNumber: 240, chapterCount: 31),
  Book(title: 'Ecclesiastes', shortName: 'Eccl', bookNumber: 250, chapterCount: 12),
  Book(title: 'Song of Solomon', shortName: 'Song', bookNumber: 260, chapterCount: 8),
  Book(title: 'Isaiah', shortName: 'Isa', bookNumber: 290, chapterCount: 66),
  Book(title: 'Jeremiah', shortName: 'Jer', bookNumber: 300, chapterCount: 52),
  Book(title: 'Lamentations', shortName: 'Lam', bookNumber: 310, chapterCount: 5),
  Book(title: 'Ezekiel', shortName: 'Ezek', bookNumber: 330, chapterCount: 48),
  Book(title: 'Daniel', shortName: 'Dan', bookNumber: 340, chapterCount: 12),
  Book(title: 'Hosea', shortName: 'Hos', bookNumber: 350, chapterCount: 14),
  Book(title: 'Joel', shortName: 'Joel', bookNumber: 360, chapterCount: 3),
  Book(title: 'Amos', shortName: 'Am', bookNumber: 370, chapterCount: 9),
  Book(title: 'Obadiah', shortName: 'Oba', bookNumber: 380, chapterCount: 1),
  Book(title: 'Jonah', shortName: 'Jona', bookNumber: 390, chapterCount: 4),
  Book(title: 'Micah', shortName: 'Mic', bookNumber: 400, chapterCount: 7),
  Book(title: 'Nahum', shortName: 'Nah', bookNumber: 410, chapterCount: 3),
  Book(title: 'Habakkuk', shortName: 'Hab', bookNumber: 420, chapterCount: 3),
  Book(title: 'Zephaniah', shortName: 'Zeph', bookNumber: 430, chapterCount: 3),
  Book(title: 'Haggai', shortName: 'Hag', bookNumber: 440, chapterCount: 2),
  Book(title: 'Zechariah', shortName: 'Zech', bookNumber: 450, chapterCount: 14),
  Book(title: 'Malachi', shortName: 'Mal', bookNumber: 460, chapterCount: 4),
  Book(title: 'Matthew', shortName: 'Mat', bookNumber: 470, chapterCount: 28),
  Book(title: 'Mark', shortName: 'Mar', bookNumber: 480, chapterCount: 16),
  Book(title: 'Luke', shortName: 'Luk', bookNumber: 490, chapterCount: 24),
  Book(title: 'John', shortName: 'John', bookNumber: 500, chapterCount: 21),
  Book(title: 'Acts', shortName: 'Acts', bookNumber: 510, chapterCount: 28),
  Book(title: 'Romans', shortName: 'Rom', bookNumber: 520, chapterCount: 16),
  Book(title: '1 Corinthians', shortName: '1Cor', bookNumber: 530, chapterCount: 16),
  Book(title: '2 Corinthians', shortName: '2Cor', bookNumber: 540, chapterCount: 13),
  Book(title: 'Galatians', shortName: 'Gal', bookNumber: 550, chapterCount: 6),
  Book(title: 'Ephesians', shortName: 'Eph', bookNumber: 560, chapterCount: 6),
  Book(title: 'Philippians', shortName: 'Phil', bookNumber: 570, chapterCount: 4),
  Book(title: 'Colossians', shortName: 'Col', bookNumber: 580, chapterCount: 4),
  Book(title: '1 Thessalonians', shortName: '1Ths', bookNumber: 590, chapterCount: 5),
  Book(title: '2 Thessalonians', shortName: '2Ths', bookNumber: 600, chapterCount: 3),
  Book(title: '1 Timothy', shortName: '1Tim', bookNumber: 610, chapterCount: 6),
  Book(title: '2 Timothy', shortName: '2Tim', bookNumber: 620, chapterCount: 4),
  Book(title: 'Titus', shortName: 'Tit', bookNumber: 630, chapterCount: 3),
  Book(title: 'Philemon', shortName: 'Phlm', bookNumber: 640, chapterCount: 1),
  Book(title: 'Hebrews', shortName: 'Heb', bookNumber: 650, chapterCount: 13),
  Book(title: 'James', shortName: 'Jam', bookNumber: 660, chapterCount: 5),
  Book(title: '1 Peter', shortName: '1Pet', bookNumber: 670, chapterCount: 5),
  Book(title: '2 Peter', shortName: '2Pet', bookNumber: 680, chapterCount: 3),
  Book(title: '1 John', shortName: '1Jn', bookNumber: 690, chapterCount: 5),
  Book(title: '2 John', shortName: '2Jn', bookNumber: 700, chapterCount: 1),
  Book(title: '3 John', shortName: '3Jn', bookNumber: 710, chapterCount: 1),
  Book(title: 'Jude', shortName: 'Jud', bookNumber: 720, chapterCount: 1),
  Book(title: 'Revelation', shortName: 'Rev', bookNumber: 730, chapterCount: 22),
];
